[package]
name = "nakala"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = { version = "4.7.0", features = ["fancy"] }
parser = { path = "../parser" } 
reedline = "0.5.0"
