[package]
name = "engine"
version = "0.1.0"
authors = ["Reagan McFarland <reagan.mcfarland1059@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hir = {path = "../hir" }
nu-ansi-term = "0.34"
